doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
    custom_template: '%kernel.project_dir%/templates/doctrine/migration.tpl'
