services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_api
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
